// functions/regex/secrets.js

// --- generic secret regex patterns ---
const genericSecrets = [
  `\\b(?:api[_-]?key|access[_-]?token|refresh[_-]?token|auth[_-]?token|client[_-]?secret|app[_-]?secret|password|passwd|pwd|secret|signing[_-]?key|encryption[_-]?key|private[_-]?key|stripe[_-]?key|twilio[_-]?token|sendgrid[_-]?api[_-]?key|aws[_-]?access[_-]?key[_-]?id|aws[_-]?secret[_-]?access[_-]?key|gcp[_-]?api[_-]?key|azure[_-]?key|service[_-]?account|sentry[_-]?dsn|slack[_-]?token)\\b\\s*[:=]\\s*["']?[a-zA-Z0-9+/=_\\-]{8,}["']?`,
  `\\beyJ[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+\\b`,
  `-----BEGIN (?:RSA|EC|DSA|OPENSSH|PRIVATE) KEY-----`,
  `-----BEGIN RSA PRIVATE KEY-----[\\s\\S]+?-----END RSA PRIVATE KEY-----`,
  `-----BEGIN DSA PRIVATE KEY-----[\\s\\S]+?-----END DSA PRIVATE KEY-----`,
  `-----BEGIN (?:EC|ECDSA) PRIVATE KEY-----[\\s\\S]+?-----END (?:EC|ECDSA) PRIVATE KEY-----`,
  `-----BEGIN ENCRYPTED PRIVATE KEY-----[\\s\\S]+?-----END ENCRYPTED PRIVATE KEY-----`,
  `-----BEGIN PGP PRIVATE KEY BLOCK-----[\\s\\S]+?-----END PGP PRIVATE KEY BLOCK-----`,
  `PuTTY-User-Key-File-2: ssh-(?:rsa|dss)\\s*Encryption: (?:none|aes)[\\s\\S]*?Private-MAC:`,
  `\\bAKIA[0-9A-Z]{16}\\b`,
  `(?:secret[-_]?access[-_]?key|SECRET[-_]?ACCESS[-_]?KEY|private[-_]?key|SecretAccessKey)[^a-zA-Z0-9]{0,20}[a-zA-Z0-9+/]{40}\\b`,
  `(facebook_secret|FACEBOOK_SECRET|facebook_app_secret|FACEBOOK_APP_SECRET)[^a-zA-Z0-9]{0,5}[a-f0-9]{32}`,
  `(GITHUB_SECRET|GITHUB_KEY|github_secret|github_key|github_token|GITHUB_TOKEN|github_api_key|GITHUB_API_KEY)[^a-zA-Z0-9]{0,10}[a-zA-Z0-9]{40}`,
  `(heroku_api_key|HEROKU_API_KEY|heroku_secret|HEROKU_SECRET)[^a-zA-Z0-9-]{0,10}\\w{8}(?:-\\w{4}){3}-\\w{12}`,
  `(slack_api_key|SLACK_API_KEY|slack_key|SLACK_KEY)[^a-f0-9]{0,10}[a-f0-9]{32}`,
  `(xox[pb](?:-[a-zA-Z0-9]+){4,})`
  // … you can append more generic secret patterns here if needed
];

// --- massive sensitive fields list ---
const sensitiveFields = [
  "input stripe token","credentialsinput","context","totp_code_field","field totp code",
  "bank-account[routing-number]-input","security_token_input","last four ssn","authtokenfield",
  "receiverstatecode","address2","otp","2fa_pin_field","cc-num","totp-pin-field","input",
  "security_pin_input","fieldpassword1","input bank account[routing number]","raw-input",
  "api_key_field"," csrf input","house number","salt_input","referraltoken","newpasswordinput",
  "field password confirm","input routing acc number","referrer","input_card[cvv]","fieldssn",
  "card_number_last_four","credentials-input","input password confirm","referrerslastname",
  "field-csrf","input-account-number","credit_card_num","bank_account_number",
  "account bank number input","token","routingnumberinput","bankacc[routingnum]field",
  "bankacc[routingnum]","-csrf-token","field-password1","repeat","field-auth-token","certinput",
  "totp-pin","fieldcert","account_routing_number","input_social_security_num","field_password2",
  "authenticity-token","cc_number_input","input-ssn","client secret","input card num",
  "field two factor token","access token input","country code","phone","field-creds","totp-pin-input",
  "input-cert","card number last4","inputroutingaccountnumber","routing_acc","avatar","json",
  "funding-source-id","field-routing-number","passwd-confirm-field","card_cvv","input totp token",
  "secretfield","2fa_token_input","input two factor token","inputcardnum","sender_id",
  "input_mysql_pwd","field-bank-account[routing-number]","input_creds","routingaccinput",
  "input cc num","emaildomain","acc[routing","credit_card_number_field","totp_token_input",
  "field_two_factor_code","input_confirm_password","memberquestionredacted","field-certificate",
  "fieldbankacc[routingnumber]","expiration","ssn","issuer-certificate","input bank acc num",
  "field__csrf","field-passwd-confirm","social-security-num","2fa_token_field","sender_address",
  "sender-address","routing-acc-num-input","bankaccnumberfield","otp input","fieldcardnumber",
  "pin-code","twofactorcodefield","acc-number","stripe_token_field","security code field",
  "phone_number","bank account number input","field_otp","totptoken","pwdinput","issuer_certificate_input",
  "privatekey","social-security-number-input","cc_num_field","input_bank_acc[routing_number]",
  "cvc-number","field-totp-token","input_totp_pin","receiverdevicecontactname","two_factor_pin",
  "issuercertificatefield","api-token-field","compensation","csrfinput","field card cvv",
  "inputaccnumber","field-cc-number","oldpassword","fieldotpcode","input cc number","input-api-token",
  "debit_card","input-routing-account-number","inputraw","otp_pin_input","bank acc","api-token-input",
  "input-access-token","card-num","field_credentials","field two factor pin","account-number-input",
  "cardnuminput","two_factor_code_input","input_cc_num","field account routing number","middlename",
  "bankaccountnumfield","credit-card-num-field","2fa token field","line2","cc-num-input","type",
  "fieldtotptoken","credit","credit card field","input two factor code","fieldtwofactorcode",
  "newpasswordfield","cc_num","bankaccfield","bank account[routing number] field","resetpasswordtoken",
  "user token","account bank number field","bankaccnumber","input-otp-token","field-bank-acc-number",
  "matches_ssn_digest","member_question","field_totp_pin","referral url","idtoken","input_two_factor_pin",
  "field_otp_token","expiry_date","client","input card[num]","routing-acc","stripe","contract",
  "auth_token_input","link","response","resetpassword","input2fa","inputbankacc[routingnumber]",
  "2fapininput","api secret","input_card_num","cc number input","otp_token_input","fieldrepeatpassword",
  "country","rate","cvv_number","contract id","input token","field_bank_acc[routing_num]",
  "email domain","confirm passwd field","field_confirm_password","input-bank-acc-num","acc_number_field",
  "password1","inputcardcvv","field_credit_card_number","salt-field","confirm-password","stripe token",
  "passwdconfirminput","creditcardnumber","input_security_code","pwd input","value","input_credit_card_number",
  "field 2fa pin","templatelink","inputsocialsecuritynum","fieldotptoken","key","city","otp pin field",
  "email","format","set-cookie","inputcvv","sender-zip-code","field_card_number","cc-number-input",
  "password_confirm","input_password","input bank acc[routing number]","field stripe token","rawfield",
  "csrf field","acc number","routing_acc_input","pay","authenticity_token","card-cvv","input security pin",
  "security_pin_field","routingnumber","field2fa","input-pwd","input bank account num","passwordconfirmfield",
  "bin","sender ip address","input-totp-pin","api","2fa_field"," csrf","api_key_input","private-key",
  "fieldcard[num]","fieldbankaccountnumber","account-bank-number-input","version","api-key","field-card[num]",
  "key input","confirmpasswordinput","passcode","card last 4","cc number field","field_bank_account_num",
  "given","field routing acc","field-password2","repeatpasswordfield","referral_token","input_key","account_number",
  "otp pin","routing-acc-number-field","receiver-identifier","card[cvv]input","2fatokeninput","otp-code",
  "field_card_cvv","debit-card","referrersavatarurl","card_number_input","groupid","otptokeninput",
  "input_passwd_confirm","response json","bankaccountnumberinput","raw field","passw","secretinput","totp field",
  "input_access_token","authenticitytoken","encrypted-password","bank-acc-number-input","bank-account[routing-number]",
  "apitokenfield","cc","field bank acc number","field-card[number]","bank_acc_field","template_link",
  "input-passwd-confirm","input-old-password","webhook","ccnuminput","bankacc[routingnum]input","pwd-input",
  "first name","response array","encrypted","totp token input","2fa pin input","field-bank-acc[routing-number]",
  "security-pin","twofactorpinfield","input-bank-acc-number","line1","inputpassword2","contacts","fieldbankaccnum",
  "cvcnumber","inputtotptoken","account bank number","csrf-field","stripe-token","passwdconfirmfield",
  "field bank acc[routing number]","mysql-pwd-field","private_key","fieldcard[number]","feature_store",
  "social security number","segment","password2-input","field-card-number"," key","repeatpassword",
  "inputcardnumber","input 2fa pin","field_2fa_code","routingaccountnumberinput","input password1",
  "account number","input_2fa_code","merchant","input-password1","auth token field","pan-bin",
  "raw_webhook_response","two-factor-code-input","otp-token","referrers-avatar-url","2fa_pin_input",
  "credit_card_num_input","inputrepeatpassword","field secret","bank_account[routing_number]_field",
  "postal","confirm_passwd","field_security_code","bankacc[routingnumber]field","country-code",
  "field_card[cvv]","private-key-field","postal_code","bank_acc[routing_num]_field","field routing acc num",
  "bank-acc-input","fieldccnum","account_number_field","stated_income","cvv input","date_of_birth",
  "login","inputpasswdconfirm","state-code","passwd confirm field","field otp code","inputcreditcardnum",
  "input password","totp-token-field","gross pay amount","card number","bank account number field","old",
  "code","creds_input","rawwebhookresponse","api key input","totppinfield","category","otptoken",
  "ssn input","rule_format","input passwd confirm","passwd_input","receiver address","routing_number_field",
  "input_bank_acc_num","access-token","private","question","input-security-token","field cert",
  "receiver zip code","account number input","2fapinfield","last-4-ssn","accnumberfield","field-passwd",
  "input_2fa_token","input totp code","inputoldpassword","field_auth_token","credit-card-number-field",
  "field confirm passwd","expiration_date","field_2fa","repeat-password-input","inputroutingacc","otp-input",
  "social_security_number","inputapikey","debit","house","old password input","responsejson","mysql",
  "field_bank_acc_number","field_csrf","field auth token","apitokeninput","passwd-field","last 4 ssn",
  "totp_token_field","security","card[number]_field","field_salt","otp-token-input","fieldoldpassword",
  "input routing account number","last","mobile","routing_account_number_input","device_id",
  "compensation_amount","full-name","receiver_state_code","challenge","x client data","pin_input",
  "security-code-field","access token","input two factor pin","mysqlpwdfield","new password",
  "private key input","membername","social security num field","input-social-security-num",
  "totp-token-input","bank account field","salt","authtoken","last4ssn","fieldtwofactortoken",
  "group-id","field credit card","routing-number-input","field-access-token","key-field",
  "input-auth-token","password_input","security-token","bank-account-input","pin-input",
  "two factor token input","key_field","uuid","bank acc[routing num] input","new-password-input",
  "field-security-token","acc number field","member_question_redacted","two factor code field",
  "field_ssn","fieldcreds","primary_account_number","inputotpcode","field_pwd","keyinput",
  "new_password","fundingsourceid","inputtotppin","password1-field","card_last_4","contractid",
  "input mysql pwd","setcookie","input_pwd","pin","property_id","zip-code","cc_num_input",
  "input-otp-code","accountbanknumberinput","totp_code","field repeat password","house details",
  "routing number input","two-factor-token","field_bank_acc[routing_number]","member question redacted",
  "input_card[number]","receiver state code","statecode","input-2fa-pin","referrers-first-name",
  "totp-code-input","receiver_ip_address","csrf-input","bankaccountinput","pininput",
  "fieldaccountroutingnumber","password_confirm_field","routing_acc_number","facetid",
  "card_num_input","account_bank_number_field","last_four","password2_input","cert","mysql-pwd",
  "otp code field","cert-field","bank_account_field","ccnumber","2fa pin field","bank-acc-number-field",
  "confirm","repeat password field","bank account","two_factor_code_field","field_bank_account",
  "reset-password","input-csrf","stripe-token-input","input-routing-acc","bank_acc[routing_num]_input",
  "password_confirm_input","otppinfield","rawinput","field token","field","totp-input",
  "bank_acc_number","confirmpasswdinput","check-amount","mysql pwd","raw input","field passwd",
  "field-security-code","socialsecuritynumberinput","card[number] field","details","totpcodefield",
  "social_security_number_field","security token","otp-pin-field","input_ssn","social-security-number",
  "inputcard[number]","url","expiry","creds_field","stated income","routingaccnumberfield",
  "phone-number","2fa_token","password","id-token","passwordfield","2fa_code","input-totp-token",
  "field 2fa","feedback","sender-id","field-credit-card","fieldroutingaccountnumber","identifier",
  "twofactortoken","security pin","middle","mysql_pwd_input","account_bank_number_input","crypt",
  "field bank account[routing number]","input2fatoken","pan bin","field-card-cvv","creds-field",
  "cardexpiration","field-mysql-pwd","fieldsocialsecuritynumber","csrf input","sender-device-id",
  "access_token_input","debit card","contact","private_key_input","input_otp_token",
  "bank_acc_num_input","account routing number","field otp","2fa input","token-input","matches",
  "id","input_routing_account_number","field salt","lastfourssn","field pwd","inputaccountroutingnumber",
  "field_certificate","input social security num","inputcard[cvv]","array","confirm_password_input",
  "authorization","input account number","cert input","field_old_password","routingaccountnumberfield",
  "creditcard","input otp pin","field-otp-token","auth-token-field","password-confirm","secret-input",
  "input-password2","field2facode","cvvfield","account[routing","credit-card-input","routing",
  "field-totp-code","password2_field","set","cardnumberfield","certificateinput","receiver-state-code",
  "certificate","4","stripetoken","field api key","input2facode","cvc_number","csrf_input",
  "inputprivatekey","otp-code-input","sendername","primaryaccountnumber","expiration-date",
  "bank-account-num-field","input_routing_acc","input-2fa-token","input-card[cvv]",
  "password1 field","field new password","bank acc number field","otp pin input","input-raw",
  "pin-field","bankaccountfield","ssnfield","input-account-bank-number","-key","passwordconfirm",
  "field-two-factor-code","two factor code","fieldcard[cvv]","bank acc[routing number] field",
  "field social security number","secret_input","totpfield","routing acc number input",
  "password2","password1_input","bank-acc[routing-number]","2fa_code_field","field-token",
  "input credit card num","bank_account[routing_number]_input","field-api-token","input-2fa-code",
  "field passwd confirm","credit-card-field","inputcreditcard","input credentials","sender-name",
  "date ofbirth","input_api_token","pan_last_4","field-routing-acc-number","field-cvv","inputbankaccountnum",
  "field_cc_number","confirm password input","input_cvv","user_ip","pay friend id","routingaccnum",
  "input_cert","bank acc[routing num]","email address","routingaccnumber","input-card[num]",
  "input_bank_acc","user_ip_address","field_totp_token","passwd input","creditcardnumberinput","mfa",
  "lname","input-credit-card-number","issuer_certificate"," csrf field","bank account[routing number]",
  "field_passwd","field-old-password","fieldroutingacc","securitycodefield","employername","inputcert",
  "two factor token","cvv-input","property name","password-confirm-field","inputkey","input-bank-acc[routing-num]",
  "card-num-input","field account bank number","issuer","fieldcreditcardnumber","input 2fa","device id",
  "totp-code","creditcardnuminput","field-pwd","old_password","state_code","otp-code-field",
  "referrers last name","credit_card_field","old-password-input","fieldroutingnumber","routingacc",
  "-csrf-input","input social security number","routing acc num input","credit card number input",
  "token field","referrers-last-name","field-bank-acc-num","input_security_token","creditcardnum",
  "card num","merchant_name","bank-acc","employer name","input cvv","sender_device_id","field_routing_acc",
  "routing acc num","routing acc number field","ofbirth","totp token field","bankaccount","inputsalt",
  "bankaccnum","comments","credit card number field","security-token-input","bankaccountnum",
  "password1 input","privatekeyinput","routing_acc_number_input","cvv number","certificate-field",
  "stated","fieldtotpcode","field card[number]","pwd_field","agent email","field_cvv","pan-last-4",
  "code_verifier","sender id","housedetails","key-input","input-cc-num","2fa-code-field","field-acc-number",
  "input_routing_acc_num","card cvv field","field-two-factor-token","reset password token","private key",
  "member name","referrers first name","bankaccountnumberfield","first","input  csrf","input ssn",
  "totp-field","otp field","firstname","mysql pwd field","auth token input","inputtwofactortoken",
  "security_token","accountnumber","state code","field_account_routing_number","confirm_passwd_field",
  "input-otp-pin","receiver-zip-code","field bank account number","input-mysql-pwd","field routing account number",
  "acc_number_input","code-verifier","totppin","card[number]-field","field_private_key","last-four-ssn",
  "insurer_name","routing-acc-num-field","useripaddress","xclientdata","repeat-password-field",
  "receiver device contact name","social-security-number-field","receiver_device_contact_name","num]",
  "credit-card-number","mobile phone","senderzipcode","input card[cvv]","credit_card_num_field","device",
  "template link","input_totp_token","matchesssndigest","acc_number","bank-acc[routing-num]-field",
  "input-bank-acc[routing-number]","inputbankaccount[routingnumber]","secret input","fieldconfirmpassword",
  "api key field","authenticity","routing acc","input_stripe_token","otp_input","2fa code input","cardnum",
  "accountbanknumber","fieldroutingaccnumber","authenticity token","password-field","field_stripe_token",
  "input_acc_number","postalcode","bankaccnumberinput","middle-name","cardsecuritycode","2fa-pin-field",
  "card_number"
];

// Escape special regex characters in field names
function escapeRegex(str) {
  return str.replace(/[-[\]/{}()*+?.\\^$|]/g, '\\$&');
}

// Build the mega regex
const sensitiveRegex = new RegExp(
  [...genericSecrets, ...sensitiveFields.map(escapeRegex)].join('|'),
  'gi'
);

// Export for usage
module.exports = sensitiveRegex;

// Example usage
// console.log(sensitiveRegex.test('input stripe token')); // true
// console.log(sensitiveRegex.test('not-a-secret')); // false
